### PR TITLE
Gui - opencore 0.7.5

### PR DESCRIPTION
**Pull request by Brooke9537**
* Based on opencore 0.7.5 Release version 
* Use GoldenGate GUI
* Thunderbolt Hot Swap

### CODE REVIEW

**Comment by zearp** [comment]
Very interesting but I can't test Thunderbolt hot swapping myself. How did you make it work without patching the Thunderbolt controller firmware?

I see many other changes too, I would need some more details on them. As it stands now the EFI works perfectly except for Thunderbolt hot plug. I'd be interested in just using whatever it is that fixes hot plugging. 

I'm not having much time lately due to work but when I have some free time I will check out the changes in more detail. I would still like some more information on the other changes. Some config changes conflict with the current config on the repo which uses the latest OpenCore sources (0.7.6).

**Comment by zearp** [comment]
Oh, I noticed you used the gui branch, which I forgot to delete a long time ago. Can you change the PR to use the current main branch?

**Comment by zearp** [comment]
I'm still interested in how you fixed the Tb3 hotplug without patching the firmware. Can you elaborate and maybe open a new PR based on the main brach?

**Comment by Brooke9537** [comment]
Sorry for the late reply.
I just use `IOElectrify.kext` and now I can charge my phone at any time.
image
the screens in my work office do not have any dp port so i do not know Whether the dp port is working properly.
you can try my EFI in https://github.com/Brooke9537/Nucintosh Forked from your repo.

**Comment by zearp** [comment]
I can charge my phone at any time without patching any system or adding new kexts. I don’t understand what that has to do with Thunderbolt hotplug.

**Pull request closed without merging**
